#!/usr/bin/env python3
"""Generate demo artifacts from the OneRoster core dictionary source."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dictionary" / "oneroster-core.v1.json"
SQL_OUT = ROOT / "schema" / "generated" / "oneroster_core_comments.sql"
OPENAPI_OUT = ROOT / "openapi" / "generated" / "oneroster-core.v0.json"
STATIC_OPENAPI_OUT = ROOT / "openapi" / "generated" / "oneroster-core-static.v0.json"
MARKDOWN_OUT = ROOT / "docs" / "generated" / "oneroster-core-dictionary.md"
HTML_OUT = ROOT / "site" / "docs" / "oneroster-core-dictionary.html"


TYPE_MAP = {
    "text": "string",
    "datetime": "string",
    "date": "string",
    "integer": "integer",
    "number": "number",
    "enum": "string",
}


def main() -> None:
    data = json.loads(SOURCE.read_text())
    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN_OUT.parent.mkdir(parents=True, exist_ok=True)
    HTML_OUT.parent.mkdir(parents=True, exist_ok=True)

    markdown = render_markdown(data)
    SQL_OUT.write_text(render_sql_comments(data))
    OPENAPI_OUT.write_text(json.dumps(render_openapi(data), indent=2) + "\n")
    STATIC_OPENAPI_OUT.write_text(json.dumps(render_static_openapi(data), indent=2) + "\n")
    MARKDOWN_OUT.write_text(markdown)
    HTML_OUT.write_text(render_html(data, markdown))

    print(f"generated {SQL_OUT.relative_to(ROOT)}")
    print(f"generated {OPENAPI_OUT.relative_to(ROOT)}")
    print(f"generated {STATIC_OPENAPI_OUT.relative_to(ROOT)}")
    print(f"generated {MARKDOWN_OUT.relative_to(ROOT)}")
    print(f"generated {HTML_OUT.relative_to(ROOT)}")


def render_sql_comments(data: dict) -> str:
    lines = [
        "-- Generated by scripts/generate_oneroster_core.py.",
        "-- Source: dictionary/oneroster-core.v1.json.",
        "-- These comments prove the dictionary can drive SQL documentation.",
        "",
    ]
    for obj in data["objects"]:
        table = obj["table_name"]
        lines.append(f"COMMENT ON TABLE demo.{table} IS {sql_quote(obj['plain_description'])};")
        for field in obj["fields"]:
            lines.append(
                f"COMMENT ON COLUMN demo.{table}.{field['column_name']} IS "
                f"{sql_quote(field['plain_description'])};"
            )
        lines.append("")
    return "\n".join(lines)


def render_openapi(data: dict) -> dict:
    schemas = {}
    paths = {
        "/health": {
            "get": {
                "tags": ["Demo"],
                "summary": "Check demo API health",
                "responses": {"200": {"description": "Demo API is running."}},
            }
        },
        "/sql/query": {
            "post": {
                "tags": ["SQL"],
                "summary": "Run a read-only SQL query against the demo database",
                "description": "Accepts SELECT or WITH queries only. This is the JSON wrapper for the relational demo layer.",
                "requestBody": {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["sql"],
                                "properties": {
                                    "sql": {
                                        "type": "string",
                                        "examples": [
                                            "select display_name, primary_role from people order by display_name"
                                        ],
                                    }
                                },
                            }
                        }
                    },
                },
                "responses": {
                    "200": {
                        "description": "Rows returned by the query.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/SqlQueryResult"}
                            }
                        },
                    },
                    "400": {"description": "The query was not accepted."},
                },
            }
        },
    }

    for obj in data["objects"]:
        schema_name = pascal(obj["object_key"])
        schemas[schema_name] = object_schema(obj, data)
        collection_response = {
            "type": "object",
            "required": ["items"],
            "properties": {
                "items": {"type": "array", "items": {"$ref": f"#/components/schemas/{schema_name}"}},
                "count": {"type": "integer"},
            },
        }
        paths[obj["api_path"]] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"List {obj['name']} records",
                "description": obj["plain_description"],
                "parameters": [
                    {
                        "name": "q",
                        "in": "query",
                        "required": False,
                        "description": "Plain text search over common display fields.",
                        "schema": {"type": "string"},
                    }
                ],
                "responses": {
                    "200": {
                        "description": f"{obj['name']} records.",
                        "content": {"application/json": {"schema": collection_response}},
                    }
                },
            }
        }
        paths[f"{obj['api_path']}/{{id}}"] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"Get one {obj['name']} record",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": True,
                        "description": f"Platform ID for the {obj['name']} record.",
                        "schema": {"type": "string"},
                    }
                ],
                "responses": {
                    "200": {
                        "description": f"One {obj['name']} record.",
                        "content": {
                            "application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}
                        },
                    },
                    "404": {"description": "Record not found."},
                },
            }
        }

    schemas["SqlQueryResult"] = {
        "type": "object",
        "required": ["columns", "rows", "count"],
        "properties": {
            "columns": {"type": "array", "items": {"type": "string"}},
            "rows": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
            "count": {"type": "integer"},
        },
    }

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Platform OneRoster Core Demo API",
            "version": "0.1.0",
            "summary": "Working OneRoster core API generated from the OneRoster core dictionary source.",
            "description": "This OpenAPI document is generated from dictionary/oneroster-core.v1.json. It describes the local Express/SQLite REST API. The GitHub Pages portal also exposes static JSON demo endpoints under https://andymontgomery-byte.github.io/platform/site/api/.",
        },
        "servers": [
            {"url": "http://localhost:8787", "description": "Local demo API"}
        ],
        "paths": paths,
        "components": {"schemas": schemas},
    }


def render_static_openapi(data: dict) -> dict:
    schemas = {}
    paths = {
        "/health.json": {
            "get": {
                "tags": ["Demo"],
                "summary": "Check hosted static API health",
                "responses": {
                    "200": {
                        "description": "Hosted static API metadata.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "ok": {"type": "boolean"},
                                        "name": {"type": "string"},
                                        "hosting": {"type": "string"},
                                        "dictionaryVersion": {"type": "string"},
                                    },
                                }
                            }
                        },
                    }
                },
            }
        },
        "/index.json": {
            "get": {
                "tags": ["Demo"],
                "summary": "List hosted static JSON endpoints",
                "responses": {
                    "200": {
                        "description": "Endpoint index for the GitHub Pages JSON API.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "description": {"type": "string"},
                                        "note": {"type": "string"},
                                        "endpoints": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "name": {"type": "string"},
                                                    "url": {"type": "string", "format": "uri"},
                                                    "relativeUrl": {"type": "string"},
                                                },
                                            },
                                        },
                                    },
                                }
                            }
                        },
                    }
                },
            }
        },
    }

    for obj in data["objects"]:
        schema_name = pascal(obj["object_key"])
        schemas[schema_name] = object_schema(obj, data)
        collection_response = collection_schema(schema_name)
        paths[f"/{api_file_name(obj['api_path'])}"] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"Get hosted {obj['name']} records",
                "description": obj["plain_description"],
                "responses": {
                    "200": {
                        "description": f"{obj['name']} records hosted as static JSON.",
                        "content": {"application/json": {"schema": collection_response}},
                    }
                },
            }
        }

    for path, summary in [
        ("/views/class-roster.json", "Get hosted class roster view rows"),
        ("/views/gradebook-results.json", "Get hosted gradebook result view rows"),
    ]:
        paths[path] = {
            "get": {
                "tags": ["Views"],
                "summary": summary,
                "description": "A read-only view over the same seeded OneRoster demo data.",
                "responses": {
                    "200": {
                        "description": "View rows hosted as static JSON.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": ["items", "count"],
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {"type": "object", "additionalProperties": True},
                                        },
                                        "count": {"type": "integer"},
                                    },
                                }
                            }
                        },
                    }
                },
            }
        }

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Platform OneRoster Core Hosted JSON API",
            "version": "0.1.0",
            "summary": "Live GitHub Pages JSON endpoints generated from the OneRoster core dictionary source.",
            "description": "This OpenAPI document is generated from dictionary/oneroster-core.v1.json. It documents the hosted GitHub Pages JSON API, whose field descriptions come from the same dictionary source as the SQL comments and HTML dictionary.",
        },
        "servers": [
            {
                "url": "https://andymontgomery-byte.github.io/platform/site/api",
                "description": "Hosted GitHub Pages static JSON API",
            }
        ],
        "paths": paths,
        "components": {"schemas": schemas},
    }


def object_schema(obj: dict, data: dict) -> dict:
    properties = {}
    required = []
    for field in obj["fields"]:
        name = field["json_name"]
        if field.get("required"):
            required.append(name)
        schema = {
            "type": TYPE_MAP.get(field["data_type"], "string"),
            "description": field["plain_description"],
            "x-decisionId": field["decision_id"],
        }
        if field["data_type"] == "date":
            schema["format"] = "date"
        elif field["data_type"] == "datetime":
            schema["format"] = "date-time"
        values = allowed_values(field, data)
        if values:
            schema["enum"] = [item["value"] for item in values]
        properties[name] = schema
    return {
        "type": "object",
        "description": obj["plain_description"],
        "required": required,
        "properties": properties,
    }


def collection_schema(schema_name: str) -> dict:
    return {
        "type": "object",
        "required": ["items", "count"],
        "properties": {
            "items": {"type": "array", "items": {"$ref": f"#/components/schemas/{schema_name}"}},
            "count": {"type": "integer"},
            "source": {
                "type": "object",
                "properties": {
                    "objectKey": {"type": "string"},
                    "tableName": {"type": "string"},
                    "dictionary": {"type": "string"},
                },
            },
        },
    }


def render_markdown(data: dict) -> str:
    lines = [
        "# OneRoster Core Generated Dictionary",
        "",
        "Generated by `scripts/generate_oneroster_core.py` from `dictionary/oneroster-core.v1.json`.",
        "",
        data["plain_description"],
        "",
        "## Objects",
        "",
    ]
    for obj in data["objects"]:
        lines.extend(
            [
                f"### {obj['name']}",
                "",
                f"- Object key: `{obj['object_key']}`",
                f"- SQL table: `demo.{obj['table_name']}`",
                f"- API path: `{obj['api_path']}`",
                f"- Privacy class: `{obj['privacy_class']}`",
                f"- Why it exists: {obj['why_it_exists']}",
                "",
                "| Field | JSON field | Type | Required | Privacy | Decision | Layperson meaning |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for field in obj["fields"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{field['column_name']}`",
                        f"`{field['json_name']}`",
                        field["data_type"],
                        "Yes" if field.get("required") else "No",
                        field["privacy_class"],
                        f"`{field['decision_id']}`",
                        field["plain_description"],
                    ]
                )
                + " |"
            )
        value_fields = [field for field in obj["fields"] if allowed_values(field, data)]
        if value_fields:
            lines.extend(["", "#### Controlled Values", ""])
            for field in value_fields:
                lines.extend([f"Values for `{field['column_name']}`:", ""])
                lines.extend(["| Value | Label | Layperson meaning |", "| --- | --- | --- |"])
                for value in allowed_values(field, data):
                    lines.append(
                        f"| `{value['value']}` | {value['label']} | {value['plain_description']} |"
                    )
                lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_html(data: dict, markdown: str) -> str:
    rows = []
    for obj in data["objects"]:
        field_rows = []
        value_sections = []
        for field in obj["fields"]:
            field_rows.append(
                "<tr>"
                f"<td><code>{html_escape(field['column_name'])}</code></td>"
                f"<td><code>{html_escape(field['json_name'])}</code></td>"
                f"<td>{html_escape(field['data_type'])}</td>"
                f"<td>{'Yes' if field.get('required') else 'No'}</td>"
                f"<td>{html_escape(field['privacy_class'])}</td>"
                f"<td><code>{html_escape(field['decision_id'])}</code></td>"
                f"<td>{html_escape(field['plain_description'])}</td>"
                "</tr>"
            )
            values = allowed_values(field, data)
            if values:
                value_rows = "".join(
                    "<tr>"
                    f"<td><code>{html_escape(value['value'])}</code></td>"
                    f"<td>{html_escape(value['label'])}</td>"
                    f"<td>{html_escape(value['plain_description'])}</td>"
                    "</tr>"
                    for value in values
                )
                value_sections.append(
                    f"<h4>Values for <code>{html_escape(field['column_name'])}</code></h4>"
                    "<table><thead><tr><th>Value</th><th>Label</th><th>Layperson meaning</th></tr></thead>"
                    f"<tbody>{value_rows}</tbody></table>"
                )
        rows.append(
            "<section class=\"doc-card\">"
            f"<h2>{html_escape(obj['name'])}</h2>"
            f"<p>{html_escape(obj['plain_description'])}</p>"
            "<dl>"
            f"<dt>Object key</dt><dd><code>{html_escape(obj['object_key'])}</code></dd>"
            f"<dt>SQL table</dt><dd><code>demo.{html_escape(obj['table_name'])}</code></dd>"
            f"<dt>API path</dt><dd><code>{html_escape(obj['api_path'])}</code></dd>"
            f"<dt>Privacy</dt><dd><code>{html_escape(obj['privacy_class'])}</code></dd>"
            f"<dt>Why it exists</dt><dd>{html_escape(obj['why_it_exists'])}</dd>"
            "</dl>"
            "<table><thead><tr><th>Field</th><th>JSON field</th><th>Type</th><th>Required</th><th>Privacy</th><th>Decision</th><th>Layperson meaning</th></tr></thead>"
            f"<tbody>{''.join(field_rows)}</tbody></table>"
            f"{''.join(value_sections)}"
            "</section>"
        )

    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{html_escape(data['name'])}</title>\n"
        "  <link rel=\"stylesheet\" href=\"../styles.css\">\n"
        "</head>\n"
        "<body class=\"doc-page\">\n"
        "  <main class=\"doc-shell\">\n"
        "    <p class=\"eyebrow\">Generated dictionary page</p>\n"
        f"    <h1>{html_escape(data['name'])}</h1>\n"
        f"    <p class=\"doc-lede\">{html_escape(data['plain_description'])}</p>\n"
        "    <p class=\"doc-lede\">Generated from <code>dictionary/oneroster-core.v1.json</code>. "
        "The same source also emits SQL comments and OpenAPI field descriptions.</p>\n"
        f"    {''.join(rows)}\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def allowed_values(field: dict, data: dict) -> list[dict]:
    if "allowed_values" in field:
        return field["allowed_values"]
    ref = field.get("allowed_values_ref")
    if ref:
        return data.get("shared_allowed_values", {}).get(ref, [])
    return []


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def api_file_name(api_path: str) -> str:
    clean = api_path.strip("/").replace("/", "-")
    return f"{clean}.json"


def html_escape(value: object) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


if __name__ == "__main__":
    main()
