#!/usr/bin/env python3
"""Generate integration and governance artifacts from the structured dictionary."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dictionary" / "integration-governance-core.v1.json"
SQL_OUT = ROOT / "schema" / "generated" / "integration_governance_core_comments.sql"
OPENAPI_OUT = ROOT / "openapi" / "generated" / "integration-governance-core.v0.json"
MARKDOWN_OUT = ROOT / "docs" / "generated" / "integration-governance-core-dictionary.md"
HTML_OUT = ROOT / "site" / "docs" / "integration-governance-core-dictionary.html"
CURRENT_DICTIONARY_REF = f"dictionary/{SOURCE.name}"


TYPE_MAP = {
    "text": "string",
    "datetime": "string",
    "date": "string",
    "integer": "integer",
    "number": "number",
    "boolean": "boolean",
    "enum": "string",
}


def main() -> None:
    data = json.loads(SOURCE.read_text())
    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN_OUT.parent.mkdir(parents=True, exist_ok=True)
    HTML_OUT.parent.mkdir(parents=True, exist_ok=True)

    markdown = render_markdown(data)
    SQL_OUT.write_text(render_sql_comments(data))
    OPENAPI_OUT.write_text(json.dumps(render_openapi(data), indent=2) + "\n")
    MARKDOWN_OUT.write_text(markdown)
    HTML_OUT.write_text(render_html(data))

    print(f"generated {SQL_OUT.relative_to(ROOT)}")
    print(f"generated {OPENAPI_OUT.relative_to(ROOT)}")
    print(f"generated {MARKDOWN_OUT.relative_to(ROOT)}")
    print(f"generated {HTML_OUT.relative_to(ROOT)}")


def render_sql_comments(data: dict) -> str:
    lines = [
        "-- Generated by scripts/generate_integration_governance_core.py.",
        "-- Source: dictionary/integration-governance-core.v1.json.",
        "-- These comments prove the integration/governance dictionary can drive SQL documentation.",
        "",
    ]
    for obj in data["objects"]:
        table = obj["table_name"]
        lines.append(f"COMMENT ON TABLE integration.{table} IS {sql_quote(obj['plain_description'])};")
        for field in obj["fields"]:
            lines.append(
                f"COMMENT ON COLUMN integration.{table}.{field['column_name']} IS "
                f"{sql_quote(field['plain_description'])};"
            )
        lines.append("")
    return "\n".join(lines)


def render_openapi(data: dict) -> dict:
    schemas = {}
    paths = {}
    field_scope_index = build_field_scope_index(data)
    for obj in data["objects"]:
        schema_name = pascal(obj["object_key"])
        schemas[schema_name] = object_schema(obj, data, field_scope_index)
        list_operation = {
            "tags": [obj["name"]],
            "summary": f"List {obj['name']} records",
            "description": obj["plain_description"],
            "parameters": [
                {
                    "name": "q",
                    "in": "query",
                    "required": False,
                    "description": "Plain text search over integration IDs, tool names, scopes, policy names, and governance identifiers.",
                    "schema": {"type": "string"},
                }
            ],
            "responses": {
                "200": {
                    "description": f"{obj['name']} records.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["items", "count"],
                                "properties": {
                                    "items": {
                                        "type": "array",
                                        "items": {"$ref": f"#/components/schemas/{schema_name}"},
                                    },
                                    "count": {"type": "integer"},
                                },
                            }
                        }
                    },
                }
            },
        }
        security = operation_security_requirements(data, obj)
        if security:
            list_operation["security"] = security
        paths[obj["api_path"]] = {
            "get": list_operation
        }
        get_operation = {
            "tags": [obj["name"]],
            "summary": f"Get one {obj['name']} record",
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": True,
                    "description": f"Platform ID for the {obj['name']} record.",
                    "schema": {"type": "string"},
                }
            ],
            "responses": {
                "200": {
                    "description": f"One {obj['name']} record.",
                    "content": {
                        "application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}
                    },
                },
                "404": {"description": "Record not found."},
            },
        }
        if security:
            get_operation["security"] = security
        paths[f"{obj['api_path']}/{{id}}"] = {
            "get": get_operation
        }

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Platform Integration and Governance Core API",
            "version": "0.1.0",
            "summary": "Generated LTI, Security Framework, and Data Privacy API schemas from the structured integration/governance dictionary source.",
            "description": (
                "This OpenAPI document is generated from dictionary/integration-governance-core.v1.json. "
                "It documents planned LTI registration, launch, LTI Advantage service, OAuth client, "
                "scope policy, privacy sharing, consent, retention, and audit API schemas. "
                "It is not a formal LTI, Security Framework, or Data Privacy certification claim and "
                "is not executable on GitHub Pages until a backend is added."
            ),
        },
        "servers": [
            {
                "url": "https://andymontgomery-byte.github.io/platform/site",
                "description": "Portal host; integration and governance endpoints are planned documentation until backend runtime exists.",
            }
        ],
        "paths": paths,
        "components": {
            "schemas": schemas,
            "securitySchemes": {
                "platformOAuth": {
                    "type": "oauth2",
                    "description": "Generated OAuth 2.0 scope policy. Each scope is mapped to exact dictionary field references and privacy ceilings in x-oauthScopePolicies.",
                    "flows": {
                        "clientCredentials": {
                            "tokenUrl": "https://platform.example.test/oauth/token",
                            "scopes": oauth_scope_descriptions(data),
                        }
                    },
                }
            },
        },
        "x-oauthScopePolicies": data.get("oauth_scope_policies", []),
        "x-unsupported-or-deferred": data.get("unsupported_or_deferred", []),
    }


def object_schema(obj: dict, data: dict, field_scope_index: dict[str, list[str]]) -> dict:
    properties = {}
    required = []
    for field in obj["fields"]:
        name = field["json_name"]
        if field.get("required"):
            required.append(name)
        schema = {
            "type": TYPE_MAP.get(field["data_type"], "string"),
            "description": field["plain_description"],
            "x-decisionId": field["decision_id"],
            "x-privacyClass": field["privacy_class"],
            "x-oauthScopes": scopes_for_field(field_scope_index, obj["object_key"], field["field_key"]),
            "x-sourceStandard": field["sourceStandard"],
        }
        if field["data_type"] == "date":
            schema["format"] = "date"
        elif field["data_type"] == "datetime":
            schema["format"] = "date-time"
        values = allowed_values(field, data)
        if values:
            schema["enum"] = [item["value"] for item in values]
            schema["x-valueDescriptions"] = {
                item["value"]: item["plain_description"] for item in values
            }
            schema["x-valueSourceStandards"] = {
                item["value"]: item["sourceStandard"] for item in values
            }
        properties[name] = schema
    return {
        "type": "object",
        "description": obj["plain_description"],
        "x-sourceStandard": obj["sourceStandard"],
        "required": required,
        "properties": properties,
    }


def build_field_scope_index(data: dict) -> dict[str, list[str]]:
    index: dict[str, list[str]] = {}
    for policy in data.get("oauth_scope_policies", []):
        scope = policy["scope"]
        for field_ref in policy.get("dictionary_fields", []):
            index.setdefault(field_ref, [])
            if scope not in index[field_ref]:
                index[field_ref].append(scope)
    return {field_ref: sorted(scopes) for field_ref, scopes in index.items()}


def source_field_ref(object_key: str, field_key: str) -> str:
    return f"{CURRENT_DICTIONARY_REF}#{object_key}.{field_key}"


def scopes_for_field(field_scope_index: dict[str, list[str]], object_key: str, field_key: str) -> list[str]:
    return field_scope_index.get(source_field_ref(object_key, field_key), [])


def oauth_scope_descriptions(data: dict) -> dict[str, str]:
    return {
        policy["scope"]: policy["plain_description"]
        for policy in data.get("oauth_scope_policies", [])
    }


def operation_security_requirements(data: dict, obj: dict) -> list[dict[str, list[str]]]:
    object_prefix = f"{CURRENT_DICTIONARY_REF}#{obj['object_key']}."
    scopes = sorted(
        {
            policy["scope"]
            for policy in data.get("oauth_scope_policies", [])
            for field_ref in policy.get("dictionary_fields", [])
            if field_ref.startswith(object_prefix)
        }
    )
    return [{"platformOAuth": [scope]} for scope in scopes]


def render_markdown(data: dict) -> str:
    field_scope_index = build_field_scope_index(data)
    lines = [
        "# Integration and Governance Core Generated Dictionary",
        "",
        "Generated by `scripts/generate_integration_governance_core.py` from `dictionary/integration-governance-core.v1.json`.",
        "",
        data["plain_description"],
        "",
        f"Model scope: {data['model_scope']}",
        "",
        "## OAuth Scope Field Map",
        "",
        "Generated scope policies map OAuth scopes to exact dictionary fields and privacy ceilings. These rows are the source for the OpenAPI `platformOAuth` security scheme and each field's `x-oauthScopes` metadata.",
        "",
        "| Scope | Action | Privacy ceiling | Launch context | Dictionary fields | Layperson meaning |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for policy in data.get("oauth_scope_policies", []):
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{policy['scope']}`",
                    policy["allowed_action"],
                    policy["privacy_ceiling"],
                    "Yes" if policy.get("requires_launch_context") else "No",
                    format_field_refs_markdown(policy.get("dictionary_fields", [])),
                    policy["plain_description"],
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Objects",
            "",
        ]
    )
    for obj in data["objects"]:
        lines.extend(
            [
                f"### {obj['name']}",
                "",
                f"- Object key: `{obj['object_key']}`",
                f"- SQL table: `integration.{obj['table_name']}`",
                f"- API path: `{obj['api_path']}`",
                f"- Privacy class: `{obj['privacy_class']}`",
                f"- Source standard: {format_source_standard(obj['sourceStandard'])}",
                f"- Why it exists: {obj['why_it_exists']}",
                "",
                "| Field | JSON field | Type | Required | Privacy | OAuth scopes | Source standard | Decision | Layperson meaning |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for field in obj["fields"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{field['column_name']}`",
                        f"`{field['json_name']}`",
                        field["data_type"],
                        "Yes" if field.get("required") else "No",
                        field["privacy_class"],
                        format_scopes_markdown(
                            scopes_for_field(field_scope_index, obj["object_key"], field["field_key"])
                        ),
                        format_source_standard(field["sourceStandard"]),
                        f"`{field['decision_id']}`",
                        field["plain_description"],
                    ]
                )
                + " |"
            )
        value_fields = [field for field in obj["fields"] if allowed_values(field, data)]
        if value_fields:
            lines.extend(["", "#### Controlled Values", ""])
            for field in value_fields:
                lines.extend([f"Values for `{field['column_name']}`:", ""])
                lines.extend(
                    [
                        "| Value | Label | Source standard | Layperson meaning |",
                        "| --- | --- | --- | --- |",
                    ]
                )
                for value in allowed_values(field, data):
                    lines.append(
                        f"| `{value['value']}` | {value['label']} | "
                        f"{format_source_standard(value['sourceStandard'])} | "
                        f"{value['plain_description']} |"
                    )
                lines.append("")
        lines.append("")

    lines.extend(["## Unsupported or Deferred", ""])
    lines.extend(["| Area | Reason |", "| --- | --- |"])
    for item in data.get("unsupported_or_deferred", []):
        lines.append(f"| {item['area']} | {item['reason']} |")
    return "\n".join(lines).rstrip() + "\n"


def render_html(data: dict) -> str:
    field_scope_index = build_field_scope_index(data)
    cards = []
    for obj in data["objects"]:
        field_rows = []
        value_sections = []
        for field in obj["fields"]:
            scopes = scopes_for_field(field_scope_index, obj["object_key"], field["field_key"])
            field_rows.append(
                "<tr>"
                f"<td><code>{html_escape(field['column_name'])}</code></td>"
                f"<td><code>{html_escape(field['json_name'])}</code></td>"
                f"<td>{html_escape(field['data_type'])}</td>"
                f"<td>{'Yes' if field.get('required') else 'No'}</td>"
                f"<td>{html_escape(field['privacy_class'])}</td>"
                f"<td>{format_scopes_html(scopes)}</td>"
                f"<td>{html_escape(format_source_standard(field['sourceStandard']))}</td>"
                f"<td><code>{html_escape(field['decision_id'])}</code></td>"
                f"<td>{html_escape(field['plain_description'])}</td>"
                "</tr>"
            )
            values = allowed_values(field, data)
            if values:
                value_rows = "".join(
                    "<tr>"
                    f"<td><code>{html_escape(value['value'])}</code></td>"
                    f"<td>{html_escape(value['label'])}</td>"
                    f"<td>{html_escape(format_source_standard(value['sourceStandard']))}</td>"
                    f"<td>{html_escape(value['plain_description'])}</td>"
                    "</tr>"
                    for value in values
                )
                value_sections.append(
                    f"<h4>Values for <code>{html_escape(field['column_name'])}</code></h4>"
                    "<table><thead><tr><th>Value</th><th>Label</th><th>Source standard</th><th>Layperson meaning</th></tr></thead>"
                    f"<tbody>{value_rows}</tbody></table>"
                )
        cards.append(
            "<section class=\"doc-card\">"
            f"<h2>{html_escape(obj['name'])}</h2>"
            f"<p>{html_escape(obj['plain_description'])}</p>"
            "<dl>"
            f"<dt>Object key</dt><dd><code>{html_escape(obj['object_key'])}</code></dd>"
            f"<dt>SQL table</dt><dd><code>integration.{html_escape(obj['table_name'])}</code></dd>"
            f"<dt>API path</dt><dd><code>{html_escape(obj['api_path'])}</code></dd>"
            f"<dt>Privacy</dt><dd><code>{html_escape(obj['privacy_class'])}</code></dd>"
            f"<dt>Source standard</dt><dd>{html_escape(format_source_standard(obj['sourceStandard']))}</dd>"
            f"<dt>Why it exists</dt><dd>{html_escape(obj['why_it_exists'])}</dd>"
            "</dl>"
            "<table><thead><tr><th>Field</th><th>JSON field</th><th>Type</th><th>Required</th><th>Privacy</th><th>OAuth scopes</th><th>Source standard</th><th>Decision</th><th>Layperson meaning</th></tr></thead>"
            f"<tbody>{''.join(field_rows)}</tbody></table>"
            f"{''.join(value_sections)}"
            "</section>"
        )

    scope_rows = "".join(
        "<tr>"
        f"<td><code>{html_escape(policy['scope'])}</code></td>"
        f"<td>{html_escape(policy['allowed_action'])}</td>"
        f"<td>{html_escape(policy['privacy_ceiling'])}</td>"
        f"<td>{'Yes' if policy.get('requires_launch_context') else 'No'}</td>"
        f"<td>{format_field_refs_html(policy.get('dictionary_fields', []))}</td>"
        f"<td>{html_escape(policy['plain_description'])}</td>"
        "</tr>"
        for policy in data.get("oauth_scope_policies", [])
    )

    unsupported = "".join(
        "<tr>"
        f"<td>{html_escape(item['area'])}</td>"
        f"<td>{html_escape(item['reason'])}</td>"
        "</tr>"
        for item in data.get("unsupported_or_deferred", [])
    )

    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{html_escape(data['name'])}</title>\n"
        "  <link rel=\"stylesheet\" href=\"../styles.css\">\n"
        "</head>\n"
        "<body class=\"doc-page\">\n"
        "  <main class=\"doc-shell\">\n"
        "    <p class=\"eyebrow\">Generated integration and governance dictionary page</p>\n"
        f"    <h1>{html_escape(data['name'])}</h1>\n"
        f"    <p class=\"doc-lede\">{html_escape(data['plain_description'])}</p>\n"
        f"    <p class=\"doc-lede\">Model scope: {html_escape(data['model_scope'])}</p>\n"
        "    <p class=\"doc-lede\">Generated from <code>dictionary/integration-governance-core.v1.json</code>. "
        "The same source also emits SQL comments and OpenAPI field descriptions.</p>\n"
        "    <section class=\"doc-card\">\n"
        "      <h2>OAuth Scope Field Map</h2>\n"
        "      <p>Generated scope policies map OAuth scopes to exact dictionary fields and privacy ceilings. "
        "The OpenAPI document emits these same scopes in the <code>platformOAuth</code> security scheme and per-field <code>x-oauthScopes</code> metadata.</p>\n"
        "      <table><thead><tr><th>Scope</th><th>Action</th><th>Privacy ceiling</th><th>Launch context</th><th>Dictionary fields</th><th>Layperson meaning</th></tr></thead>"
        f"<tbody>{scope_rows}</tbody></table>\n"
        "    </section>\n"
        f"    {''.join(cards)}\n"
        "    <section class=\"doc-card\">\n"
        "      <h2>Unsupported or Deferred</h2>\n"
        "      <table><thead><tr><th>Area</th><th>Reason</th></tr></thead>"
        f"<tbody>{unsupported}</tbody></table>\n"
        "    </section>\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def allowed_values(field: dict, data: dict) -> list[dict]:
    if "allowed_values" in field:
        return field["allowed_values"]
    ref = field.get("allowed_values_ref")
    if ref:
        return data.get("shared_allowed_values", {}).get(ref, [])
    return []


def format_source_standard(source: dict) -> str:
    parts = [source.get("standard", ""), source.get("version", "")]
    target = ".".join(
        str(source[key])
        for key in ["object", "field", "vocabulary", "value"]
        if source.get(key)
    )
    if target:
        parts.append(target)
    coverage = source.get("coverage")
    if coverage and coverage != "mapped":
        parts.append(f"({coverage})")
    return " ".join(str(part) for part in parts if part)


def format_field_refs_markdown(field_refs: list[str]) -> str:
    if not field_refs:
        return "None"
    return ", ".join(f"`{field_ref}`" for field_ref in field_refs)


def format_scopes_markdown(scopes: list[str]) -> str:
    if not scopes:
        return "None"
    return ", ".join(f"`{scope}`" for scope in scopes)


def format_field_refs_html(field_refs: list[str]) -> str:
    if not field_refs:
        return "None"
    return "<br>".join(f"<code>{html_escape(field_ref)}</code>" for field_ref in field_refs)


def format_scopes_html(scopes: list[str]) -> str:
    if not scopes:
        return "None"
    return "<br>".join(f"<code>{html_escape(scope)}</code>" for scope in scopes)


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def html_escape(value: object) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


if __name__ == "__main__":
    main()
