#!/usr/bin/env python3
"""Generate QTI repository artifacts from the structured QTI dictionary."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dictionary" / "qti-core.v1.json"
SQL_OUT = ROOT / "schema" / "generated" / "qti_core_comments.sql"
OPENAPI_OUT = ROOT / "openapi" / "generated" / "qti-core.v0.json"
MARKDOWN_OUT = ROOT / "docs" / "generated" / "qti-core-dictionary.md"
HTML_OUT = ROOT / "site" / "docs" / "qti-core-dictionary.html"


TYPE_MAP = {
    "text": "string",
    "datetime": "string",
    "date": "string",
    "integer": "integer",
    "number": "number",
    "enum": "string",
}


def main() -> None:
    data = json.loads(SOURCE.read_text())
    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN_OUT.parent.mkdir(parents=True, exist_ok=True)
    HTML_OUT.parent.mkdir(parents=True, exist_ok=True)

    markdown = render_markdown(data)
    SQL_OUT.write_text(render_sql_comments(data))
    OPENAPI_OUT.write_text(json.dumps(render_openapi(data), indent=2) + "\n")
    MARKDOWN_OUT.write_text(markdown)
    HTML_OUT.write_text(render_html(data))

    print(f"generated {SQL_OUT.relative_to(ROOT)}")
    print(f"generated {OPENAPI_OUT.relative_to(ROOT)}")
    print(f"generated {MARKDOWN_OUT.relative_to(ROOT)}")
    print(f"generated {HTML_OUT.relative_to(ROOT)}")


def render_sql_comments(data: dict) -> str:
    lines = [
        "-- Generated by scripts/generate_qti_core.py.",
        "-- Source: dictionary/qti-core.v1.json.",
        "-- These comments prove the QTI dictionary can drive SQL documentation.",
        "",
    ]
    for obj in data["objects"]:
        table = obj["table_name"]
        lines.append(f"COMMENT ON TABLE assessment.{table} IS {sql_quote(obj['plain_description'])};")
        for field in obj["fields"]:
            lines.append(
                f"COMMENT ON COLUMN assessment.{table}.{field['column_name']} IS "
                f"{sql_quote(field['plain_description'])};"
            )
        lines.append("")
    return "\n".join(lines)


def render_openapi(data: dict) -> dict:
    schemas = {}
    paths = {}
    for obj in data["objects"]:
        schema_name = pascal(obj["object_key"])
        schemas[schema_name] = object_schema(obj, data)
        paths[obj["api_path"]] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"List {obj['name']} records",
                "description": obj["plain_description"],
                "responses": {
                    "200": {
                        "description": f"{obj['name']} records.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": ["items", "count"],
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {"$ref": f"#/components/schemas/{schema_name}"},
                                        },
                                        "count": {"type": "integer"},
                                    },
                                }
                            }
                        },
                    }
                },
            }
        }
        paths[f"{obj['api_path']}/{{id}}"] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"Get one {obj['name']} record",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": True,
                        "description": f"Platform ID for the {obj['name']} record.",
                        "schema": {"type": "string"},
                    }
                ],
                "responses": {
                    "200": {
                        "description": f"One {obj['name']} record.",
                        "content": {
                            "application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}
                        },
                    },
                    "404": {"description": "Record not found."},
                },
            }
        }

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Platform QTI 3 Repository API",
            "version": "0.1.0",
            "summary": "Generated QTI repository API schemas from the structured QTI dictionary source.",
            "description": (
                "This OpenAPI document is generated from dictionary/qti-core.v1.json. "
                "It documents the planned QTI repository projection API. It is not a delivery/runtime "
                "conformance claim and is not executable on GitHub Pages until a backend is added."
            ),
        },
        "servers": [
            {
                "url": "https://andymontgomery-byte.github.io/platform/site",
                "description": "Portal host; QTI endpoints are planned documentation until backend runtime exists.",
            }
        ],
        "paths": paths,
        "components": {"schemas": schemas},
        "x-unsupported-or-deferred": data.get("unsupported_or_deferred", []),
    }


def object_schema(obj: dict, data: dict) -> dict:
    properties = {}
    required = []
    for field in obj["fields"]:
        name = field["json_name"]
        if field.get("required"):
            required.append(name)
        schema = {
            "type": TYPE_MAP.get(field["data_type"], "string"),
            "description": field["plain_description"],
            "x-decisionId": field["decision_id"],
        }
        if field["data_type"] == "date":
            schema["format"] = "date"
        elif field["data_type"] == "datetime":
            schema["format"] = "date-time"
        values = allowed_values(field, data)
        if values:
            schema["enum"] = [item["value"] for item in values]
            schema["x-valueDescriptions"] = {
                item["value"]: item["plain_description"] for item in values
            }
        properties[name] = schema
    return {
        "type": "object",
        "description": obj["plain_description"],
        "required": required,
        "properties": properties,
    }


def render_markdown(data: dict) -> str:
    lines = [
        "# QTI Core Generated Dictionary",
        "",
        "Generated by `scripts/generate_qti_core.py` from `dictionary/qti-core.v1.json`.",
        "",
        data["plain_description"],
        "",
        f"Model scope: {data['model_scope']}",
        "",
        "## Objects",
        "",
    ]
    for obj in data["objects"]:
        lines.extend(
            [
                f"### {obj['name']}",
                "",
                f"- Object key: `{obj['object_key']}`",
                f"- SQL table: `assessment.{obj['table_name']}`",
                f"- API path: `{obj['api_path']}`",
                f"- Privacy class: `{obj['privacy_class']}`",
                f"- Why it exists: {obj['why_it_exists']}",
                "",
                "| Field | JSON field | Type | Required | Privacy | Decision | Layperson meaning |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for field in obj["fields"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{field['column_name']}`",
                        f"`{field['json_name']}`",
                        field["data_type"],
                        "Yes" if field.get("required") else "No",
                        field["privacy_class"],
                        f"`{field['decision_id']}`",
                        field["plain_description"],
                    ]
                )
                + " |"
            )
        value_fields = [field for field in obj["fields"] if allowed_values(field, data)]
        if value_fields:
            lines.extend(["", "#### Controlled Values", ""])
            for field in value_fields:
                lines.extend([f"Values for `{field['column_name']}`:", ""])
                lines.extend(["| Value | Label | Layperson meaning |", "| --- | --- | --- |"])
                for value in allowed_values(field, data):
                    lines.append(
                        f"| `{value['value']}` | {value['label']} | {value['plain_description']} |"
                    )
                lines.append("")
        lines.append("")

    lines.extend(["## Unsupported or Deferred", ""])
    lines.extend(["| Area | Reason |", "| --- | --- |"])
    for item in data.get("unsupported_or_deferred", []):
        lines.append(f"| {item['area']} | {item['reason']} |")
    return "\n".join(lines).rstrip() + "\n"


def render_html(data: dict) -> str:
    cards = []
    for obj in data["objects"]:
        field_rows = []
        value_sections = []
        for field in obj["fields"]:
            field_rows.append(
                "<tr>"
                f"<td><code>{html_escape(field['column_name'])}</code></td>"
                f"<td><code>{html_escape(field['json_name'])}</code></td>"
                f"<td>{html_escape(field['data_type'])}</td>"
                f"<td>{'Yes' if field.get('required') else 'No'}</td>"
                f"<td>{html_escape(field['privacy_class'])}</td>"
                f"<td><code>{html_escape(field['decision_id'])}</code></td>"
                f"<td>{html_escape(field['plain_description'])}</td>"
                "</tr>"
            )
            values = allowed_values(field, data)
            if values:
                value_rows = "".join(
                    "<tr>"
                    f"<td><code>{html_escape(value['value'])}</code></td>"
                    f"<td>{html_escape(value['label'])}</td>"
                    f"<td>{html_escape(value['plain_description'])}</td>"
                    "</tr>"
                    for value in values
                )
                value_sections.append(
                    f"<h4>Values for <code>{html_escape(field['column_name'])}</code></h4>"
                    "<table><thead><tr><th>Value</th><th>Label</th><th>Layperson meaning</th></tr></thead>"
                    f"<tbody>{value_rows}</tbody></table>"
                )
        cards.append(
            "<section class=\"doc-card\">"
            f"<h2>{html_escape(obj['name'])}</h2>"
            f"<p>{html_escape(obj['plain_description'])}</p>"
            "<dl>"
            f"<dt>Object key</dt><dd><code>{html_escape(obj['object_key'])}</code></dd>"
            f"<dt>SQL table</dt><dd><code>assessment.{html_escape(obj['table_name'])}</code></dd>"
            f"<dt>API path</dt><dd><code>{html_escape(obj['api_path'])}</code></dd>"
            f"<dt>Privacy</dt><dd><code>{html_escape(obj['privacy_class'])}</code></dd>"
            f"<dt>Why it exists</dt><dd>{html_escape(obj['why_it_exists'])}</dd>"
            "</dl>"
            "<table><thead><tr><th>Field</th><th>JSON field</th><th>Type</th><th>Required</th><th>Privacy</th><th>Decision</th><th>Layperson meaning</th></tr></thead>"
            f"<tbody>{''.join(field_rows)}</tbody></table>"
            f"{''.join(value_sections)}"
            "</section>"
        )

    unsupported = "".join(
        "<tr>"
        f"<td>{html_escape(item['area'])}</td>"
        f"<td>{html_escape(item['reason'])}</td>"
        "</tr>"
        for item in data.get("unsupported_or_deferred", [])
    )

    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{html_escape(data['name'])}</title>\n"
        "  <link rel=\"stylesheet\" href=\"../styles.css\">\n"
        "</head>\n"
        "<body class=\"doc-page\">\n"
        "  <main class=\"doc-shell\">\n"
        "    <p class=\"eyebrow\">Generated QTI dictionary page</p>\n"
        f"    <h1>{html_escape(data['name'])}</h1>\n"
        f"    <p class=\"doc-lede\">{html_escape(data['plain_description'])}</p>\n"
        f"    <p class=\"doc-lede\">Model scope: {html_escape(data['model_scope'])}</p>\n"
        "    <p class=\"doc-lede\">Generated from <code>dictionary/qti-core.v1.json</code>. "
        "The same source also emits SQL comments and OpenAPI field descriptions.</p>\n"
        f"    {''.join(cards)}\n"
        "    <section class=\"doc-card\">\n"
        "      <h2>Unsupported or Deferred</h2>\n"
        "      <table><thead><tr><th>Area</th><th>Reason</th></tr></thead>"
        f"<tbody>{unsupported}</tbody></table>\n"
        "    </section>\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def allowed_values(field: dict, data: dict) -> list[dict]:
    if "allowed_values" in field:
        return field["allowed_values"]
    ref = field.get("allowed_values_ref")
    if ref:
        return data.get("shared_allowed_values", {}).get(ref, [])
    return []


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def html_escape(value: object) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


if __name__ == "__main__":
    main()
