#!/usr/bin/env python3
"""Generate demo artifacts from the OneRoster core dictionary source."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dictionary" / "oneroster-core.v1.json"
SQL_OUT = ROOT / "schema" / "generated" / "oneroster_core_comments.sql"
OPENAPI_OUT = ROOT / "openapi" / "generated" / "oneroster-core.v0.json"
MARKDOWN_OUT = ROOT / "docs" / "generated" / "oneroster-core-dictionary.md"


TYPE_MAP = {
    "text": "string",
    "datetime": "string",
    "date": "string",
    "integer": "integer",
    "number": "number",
    "enum": "string",
}


def main() -> None:
    data = json.loads(SOURCE.read_text())
    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN_OUT.parent.mkdir(parents=True, exist_ok=True)

    SQL_OUT.write_text(render_sql_comments(data))
    OPENAPI_OUT.write_text(json.dumps(render_openapi(data), indent=2) + "\n")
    MARKDOWN_OUT.write_text(render_markdown(data))

    print(f"generated {SQL_OUT.relative_to(ROOT)}")
    print(f"generated {OPENAPI_OUT.relative_to(ROOT)}")
    print(f"generated {MARKDOWN_OUT.relative_to(ROOT)}")


def render_sql_comments(data: dict) -> str:
    lines = [
        "-- Generated by scripts/generate_oneroster_core.py.",
        "-- Source: dictionary/oneroster-core.v1.json.",
        "-- These comments prove the dictionary can drive SQL documentation.",
        "",
    ]
    for obj in data["objects"]:
        table = obj["table_name"]
        lines.append(f"COMMENT ON TABLE demo.{table} IS {sql_quote(obj['plain_description'])};")
        for field in obj["fields"]:
            lines.append(
                f"COMMENT ON COLUMN demo.{table}.{field['column_name']} IS "
                f"{sql_quote(field['plain_description'])};"
            )
        lines.append("")
    return "\n".join(lines)


def render_openapi(data: dict) -> dict:
    schemas = {}
    paths = {
        "/health": {
            "get": {
                "tags": ["Demo"],
                "summary": "Check demo API health",
                "responses": {"200": {"description": "Demo API is running."}},
            }
        },
        "/sql/query": {
            "post": {
                "tags": ["SQL"],
                "summary": "Run a read-only SQL query against the demo database",
                "description": "Accepts SELECT or WITH queries only. This is the JSON wrapper for the relational demo layer.",
                "requestBody": {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["sql"],
                                "properties": {
                                    "sql": {
                                        "type": "string",
                                        "examples": [
                                            "select display_name, primary_role from people order by display_name"
                                        ],
                                    }
                                },
                            }
                        }
                    },
                },
                "responses": {
                    "200": {
                        "description": "Rows returned by the query.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/SqlQueryResult"}
                            }
                        },
                    },
                    "400": {"description": "The query was not accepted."},
                },
            }
        },
    }

    for obj in data["objects"]:
        schema_name = pascal(obj["object_key"])
        schemas[schema_name] = object_schema(obj, data)
        collection_response = {
            "type": "object",
            "required": ["items"],
            "properties": {
                "items": {"type": "array", "items": {"$ref": f"#/components/schemas/{schema_name}"}},
                "count": {"type": "integer"},
            },
        }
        paths[obj["api_path"]] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"List {obj['name']} records",
                "description": obj["plain_description"],
                "parameters": [
                    {
                        "name": "q",
                        "in": "query",
                        "required": False,
                        "description": "Plain text search over common display fields.",
                        "schema": {"type": "string"},
                    }
                ],
                "responses": {
                    "200": {
                        "description": f"{obj['name']} records.",
                        "content": {"application/json": {"schema": collection_response}},
                    }
                },
            }
        }
        paths[f"{obj['api_path']}/{{id}}"] = {
            "get": {
                "tags": [obj["name"]],
                "summary": f"Get one {obj['name']} record",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": True,
                        "description": f"Platform ID for the {obj['name']} record.",
                        "schema": {"type": "string"},
                    }
                ],
                "responses": {
                    "200": {
                        "description": f"One {obj['name']} record.",
                        "content": {
                            "application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}
                        },
                    },
                    "404": {"description": "Record not found."},
                },
            }
        }

    schemas["SqlQueryResult"] = {
        "type": "object",
        "required": ["columns", "rows", "count"],
        "properties": {
            "columns": {"type": "array", "items": {"type": "string"}},
            "rows": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
            "count": {"type": "integer"},
        },
    }

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Platform OneRoster Core Demo API",
            "version": "0.1.0",
            "summary": "Working local API generated from the OneRoster core dictionary source.",
            "description": "This OpenAPI document is generated from dictionary/oneroster-core.v1.json.",
        },
        "servers": [
            {"url": "http://localhost:8787", "description": "Local demo API"}
        ],
        "paths": paths,
        "components": {"schemas": schemas},
    }


def object_schema(obj: dict, data: dict) -> dict:
    properties = {}
    required = []
    for field in obj["fields"]:
        name = field["json_name"]
        if field.get("required"):
            required.append(name)
        schema = {
            "type": TYPE_MAP.get(field["data_type"], "string"),
            "description": field["plain_description"],
        }
        if field["data_type"] == "date":
            schema["format"] = "date"
        elif field["data_type"] == "datetime":
            schema["format"] = "date-time"
        values = allowed_values(field, data)
        if values:
            schema["enum"] = [item["value"] for item in values]
        properties[name] = schema
    return {
        "type": "object",
        "description": obj["plain_description"],
        "required": required,
        "properties": properties,
    }


def render_markdown(data: dict) -> str:
    lines = [
        "# OneRoster Core Generated Dictionary",
        "",
        "Generated by `scripts/generate_oneroster_core.py` from `dictionary/oneroster-core.v1.json`.",
        "",
        data["plain_description"],
        "",
        "## Objects",
        "",
    ]
    for obj in data["objects"]:
        lines.extend(
            [
                f"### {obj['name']}",
                "",
                f"- Object key: `{obj['object_key']}`",
                f"- SQL table: `demo.{obj['table_name']}`",
                f"- API path: `{obj['api_path']}`",
                f"- Privacy class: `{obj['privacy_class']}`",
                f"- Why it exists: {obj['why_it_exists']}",
                "",
                "| Field | JSON field | Type | Required | Privacy | Layperson meaning |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for field in obj["fields"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{field['column_name']}`",
                        f"`{field['json_name']}`",
                        field["data_type"],
                        "Yes" if field.get("required") else "No",
                        field["privacy_class"],
                        field["plain_description"],
                    ]
                )
                + " |"
            )
        value_fields = [field for field in obj["fields"] if allowed_values(field, data)]
        if value_fields:
            lines.extend(["", "#### Controlled Values", ""])
            for field in value_fields:
                lines.extend([f"Values for `{field['column_name']}`:", ""])
                lines.extend(["| Value | Label | Layperson meaning |", "| --- | --- | --- |"])
                for value in allowed_values(field, data):
                    lines.append(
                        f"| `{value['value']}` | {value['label']} | {value['plain_description']} |"
                    )
                lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def allowed_values(field: dict, data: dict) -> list[dict]:
    if "allowed_values" in field:
        return field["allowed_values"]
    ref = field.get("allowed_values_ref")
    if ref:
        return data.get("shared_allowed_values", {}).get(ref, [])
    return []


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


if __name__ == "__main__":
    main()
