-- Generated by scripts/generate_supabase_migrations.py.
-- Source: data/data-dictionary.seed.json migration_generation and objects[].relationships.
-- Decision: DEC-020-relational-graph-migrations.

begin;

drop view if exists public.gradebook_results;
drop view if exists public.class_roster;
drop function if exists public.read_people_sensitive_audited(text, text, text, text, text, text);
drop table if exists public.audit_log cascade;
drop table if exists public.source_identifiers cascade;
drop table if exists public.results cascade;
drop table if exists public.line_items cascade;
drop table if exists public.enrollments cascade;
drop table if exists public.classes cascade;
drop table if exists public.courses cascade;
drop table if exists public.academic_sessions cascade;
drop table if exists public.people cascade;
drop table if exists public.organizations cascade;

create table public.organizations (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  name text not null,
  organization_type text not null check (organization_type in ('district', 'school', 'department', 'program')),
  parent_organization_id text references public.organizations(id) on delete set null,
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.people (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  display_name text not null,
  given_name text,
  family_name text,
  email text,
  primary_role text not null check (primary_role in ('student', 'teacher', 'administrator', 'guardian')),
  enabled_user text not null check (enabled_user in ('true', 'false')),
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.academic_sessions (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  title text not null,
  session_type text not null check (session_type in ('schoolYear', 'term', 'semester', 'quarter', 'gradingPeriod')),
  start_date date not null,
  end_date date not null,
  school_year integer,
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.courses (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  title text not null,
  course_code text,
  org_id text not null references public.organizations(id),
  school_year_id text references public.academic_sessions(id),
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.classes (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  title text not null,
  class_type text not null check (class_type in ('scheduled', 'homeroom')),
  class_code text,
  course_id text not null references public.courses(id),
  school_id text not null references public.organizations(id),
  term_id text references public.academic_sessions(id),
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.enrollments (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  class_id text not null references public.classes(id),
  person_id text not null references public.people(id),
  school_id text not null references public.organizations(id),
  role text not null check (role in ('student', 'teacher', 'administrator', 'aide')),
  begin_date date,
  end_date date,
  primary_flag text check (primary_flag in ('true', 'false')),
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.line_items (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  title text not null,
  class_id text not null references public.classes(id),
  category text check (category in ('assignment', 'quiz', 'test', 'participation')),
  assign_date date,
  due_date date,
  result_value_min double precision,
  result_value_max double precision,
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.results (
  tenant_id uuid not null,
  id text primary key,
  sourced_id text not null unique,
  line_item_id text not null references public.line_items(id),
  person_id text not null references public.people(id),
  score_status text not null check (score_status in ('notSubmitted', 'submitted', 'partiallyGraded', 'fullyGraded')),
  score double precision,
  score_date timestamptz,
  comment text,
  status text not null check (status in ('active', 'inactive', 'tobedeleted')),
  date_last_modified timestamptz not null
);

create table public.source_identifiers (
  tenant_id uuid not null,
  id text primary key,
  object_type text not null,
  object_id text not null,
  source_system text not null,
  external_id text not null,
  identifier_type text not null check (identifier_type in ('oneRosterSourcedId', 'sisSourcedId', 'ltiContextId', 'ltiUserId', 'emailAddress')),
  status text not null check (status in ('active', 'inactive', 'tobedeleted'))
);

create table public.audit_log (
  tenant_id uuid not null,
  id bigint generated by default as identity primary key,
  client_id text not null,
  scope text not null,
  purpose text not null,
  field_accessed text not null,
  subject_table text not null,
  subject_id text,
  actor_user_id uuid,
  request_path text,
  request_id text,
  timestamp timestamptz not null default now()
);

create index organizations_tenant_idx on public.organizations(tenant_id);
create index organizations_parent_idx on public.organizations(parent_organization_id);
create index people_tenant_idx on public.people(tenant_id);
create index academic_sessions_tenant_idx on public.academic_sessions(tenant_id);
create index courses_tenant_idx on public.courses(tenant_id);
create index courses_org_idx on public.courses(org_id);
create index courses_school_year_idx on public.courses(school_year_id);
create index classes_tenant_idx on public.classes(tenant_id);
create index classes_course_idx on public.classes(course_id);
create index classes_school_idx on public.classes(school_id);
create index classes_term_idx on public.classes(term_id);
create index enrollments_tenant_idx on public.enrollments(tenant_id);
create index enrollments_class_idx on public.enrollments(class_id);
create index enrollments_person_idx on public.enrollments(person_id);
create index enrollments_school_idx on public.enrollments(school_id);
create index line_items_tenant_idx on public.line_items(tenant_id);
create index line_items_class_idx on public.line_items(class_id);
create index results_tenant_idx on public.results(tenant_id);
create index results_line_item_idx on public.results(line_item_id);
create index results_person_idx on public.results(person_id);
create index source_identifiers_tenant_idx on public.source_identifiers(tenant_id);
create index source_identifiers_lookup_idx on public.source_identifiers(object_type, object_id);
create index audit_log_tenant_timestamp_idx on public.audit_log(tenant_id, timestamp desc);
create index audit_log_field_idx on public.audit_log(field_accessed);

create view public.class_roster
with (security_invoker = true) as
select
  e.id as enrollment_id,
  c.id as class_id,
  c.title as class_title,
  p.id as person_id,
  p.display_name,
  p.primary_role,
  e.role as class_role,
  o.name as school_name,
  e.status
from public.enrollments e
join public.classes c on c.id = e.class_id
join public.people p on p.id = e.person_id
join public.organizations o on o.id = e.school_id;

create view public.gradebook_results
with (security_invoker = true) as
select
  r.id as result_id,
  li.title as line_item_title,
  c.title as class_title,
  p.display_name as learner_name,
  r.score_status,
  r.score,
  li.result_value_max,
  r.comment,
  r.score_date
from public.results r
join public.line_items li on li.id = r.line_item_id
join public.classes c on c.id = li.class_id
join public.people p on p.id = r.person_id;

alter table public.organizations enable row level security;
alter table public.organizations force row level security;
alter table public.people enable row level security;
alter table public.people force row level security;
alter table public.academic_sessions enable row level security;
alter table public.academic_sessions force row level security;
alter table public.courses enable row level security;
alter table public.courses force row level security;
alter table public.classes enable row level security;
alter table public.classes force row level security;
alter table public.enrollments enable row level security;
alter table public.enrollments force row level security;
alter table public.line_items enable row level security;
alter table public.line_items force row level security;
alter table public.results enable row level security;
alter table public.results force row level security;
alter table public.source_identifiers enable row level security;
alter table public.source_identifiers force row level security;
alter table public.audit_log enable row level security;
alter table public.audit_log force row level security;

-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_organizations on public.organizations for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_people on public.people for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_academic_sessions on public.academic_sessions for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_courses on public.courses for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_classes on public.classes for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_enrollments on public.enrollments for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_line_items on public.line_items for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for runtime records.
create policy demo_read_results on public.results for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for results writes.
create policy demo_insert_results on public.results for insert to authenticated with check (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  )
  and exists (
    select 1
    from public.line_items li
    where li.id = line_item_id
      and li.tenant_id = coalesce(
        nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
        nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
      )
  )
  and exists (
    select 1
    from public.people p
    where p.id = person_id
      and p.tenant_id = coalesce(
        nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
        nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
      )
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for results writes.
create policy demo_update_results on public.results for update to authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  )
) with check (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  )
  and exists (
    select 1
    from public.line_items li
    where li.id = line_item_id
      and li.tenant_id = coalesce(
        nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
        nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
      )
  )
  and exists (
    select 1
    from public.people p
    where p.id = person_id
      and p.tenant_id = coalesce(
        nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
        nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
      )
  )
);
-- decision_id: DEC-010-tenancy-reference-data; tenant-claim RLS for identifier crosswalks.
create policy demo_read_source_identifiers on public.source_identifiers for select to anon, authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid,
    case when auth.role() = 'anon' then '11111111-1111-1111-1111-111111111111'::uuid end
  )
);
-- decision_id: DEC-013-audit-response-truth; audit writes remain tenant-scoped.
create policy demo_insert_audit_log on public.audit_log for insert to authenticated with check (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  )
  and client_id <> ''
  and scope <> ''
  and purpose <> ''
  and field_accessed <> ''
);
-- decision_id: DEC-013-audit-response-truth; audited responses read back tenant-scoped rows.
create policy demo_read_audit_log on public.audit_log for select to authenticated using (
  tenant_id = coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  )
);

-- decision_id: DEC-013-audit-response-truth; sensitive reads write audit_log rows before returning data.
create function public.read_people_sensitive_audited(
  person_id text,
  client_id text,
  scope text,
  purpose text,
  request_path text default null,
  request_id text default null
)
returns table (
  id text,
  sourced_id text,
  display_name text,
  given_name text,
  family_name text,
  email text,
  primary_role text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_tenant uuid;
  safe_client_id text := nullif(btrim(client_id), '');
  safe_scope text := nullif(btrim(scope), '');
  safe_purpose text := nullif(btrim(purpose), '');
  person_row public.people%rowtype;
begin
  caller_tenant := coalesce(
    nullif(auth.jwt() ->> 'tenant_id', '')::uuid,
    nullif(auth.jwt() -> 'app_metadata' ->> 'tenant_id', '')::uuid
  );

  if caller_tenant is null then
    raise exception 'tenant_id claim is required for audited sensitive reads'
      using errcode = '28000';
  end if;

  if safe_client_id is null or safe_scope is null or safe_purpose is null then
    raise exception 'client_id, scope, and purpose are required for audited sensitive reads'
      using errcode = '22023';
  end if;

  select *
    into person_row
    from public.people p
   where p.id = person_id
     and p.tenant_id = caller_tenant;

  if not found then
    return;
  end if;

  insert into public.audit_log (
    tenant_id,
    client_id,
    scope,
    purpose,
    field_accessed,
    subject_table,
    subject_id,
    actor_user_id,
    request_path,
    request_id
  )
  select
    caller_tenant,
    safe_client_id,
    safe_scope,
    safe_purpose,
    field_name,
    'people',
    person_row.id,
    auth.uid(),
    nullif(btrim(request_path), ''),
    nullif(btrim(request_id), '')
  from unnest(array[
    'people.display_name',
    'people.given_name',
    'people.family_name',
    'people.email',
    'people.primary_role'
  ]) as audited(field_name);

  return query
  select
    person_row.id,
    person_row.sourced_id,
    person_row.display_name,
    person_row.given_name,
    person_row.family_name,
    person_row.email,
    person_row.primary_role;
end;
$$;

grant usage on schema public to anon, authenticated;
revoke all privileges on
  public.organizations,
  public.people,
  public.academic_sessions,
  public.courses,
  public.classes,
  public.enrollments,
  public.line_items,
  public.results,
  public.source_identifiers,
  public.audit_log
from anon, authenticated;
revoke all on function public.read_people_sensitive_audited(text, text, text, text, text, text) from public;

grant select on
  public.organizations,
  public.academic_sessions,
  public.courses,
  public.classes,
  public.enrollments,
  public.line_items,
  public.results,
  public.source_identifiers,
  public.class_roster,
  public.gradebook_results
to anon, authenticated;

grant select (
  tenant_id,
  id,
  sourced_id,
  display_name,
  primary_role,
  status,
  date_last_modified
) on public.people to anon, authenticated;

grant insert, update on public.results to authenticated;
grant select, insert on public.audit_log to authenticated;
grant execute on function public.read_people_sensitive_audited(text, text, text, text, text, text) to authenticated;

notify pgrst, 'reload schema';

commit;
